DigitalNutritionalAssessment/gibsonify

- lib/home/view/home_page.dart
- lib/home/widgets/sync_screen.dart
- pubspec.lock
- pubspec.yaml
PR to implement data export for testing purposes
> feat: export saved data via email

- lib/collection/bloc/collection_bloc.dart
- lib/collection/bloc/collection_event.dart
- lib/collection/view/finish_collection_page.dart
- lib/collection/view/view.dart
- lib/collection/widgets/first_pass_food_item_card.dart
- lib/collection/widgets/fourth_pass_screen.dart
- lib/collection/widgets/sensitization_screen.dart
- lib/home/widgets/collections_screen.dart
- lib/home/widgets/recipes_screen.dart
- lib/navigation/models/page_router.dart
- lib/recipe/widgets/recipe_screen.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- packages/gibsonify_api/lib/src/gibsonify_api.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.dart
This PR adds a variety of minor functionality to Collection and some accompanying Recipe changes. More fields are added to GibsonsForm and a new `FinishCollection` page is added at the end of collection. Also a bug about choosing new recipes is fixed, although there are some issues.
> feat: minor collection features

- CHANGELOG.md
- cz.yaml
- pubspec.yaml
> chore: release 1.1.0

- .fvm/fvm_config.json
- pubspec.lock
Bump Flutter SDK version to [2.10](https://scribe.rip/flutter/whats-new-in-flutter-2-10-5aafb0314b12) and correspondingly update .fvm config.
I tested the android APK and found nothing to be broken as a result of this, but please double check 😎.
> build: bump flutter and fvm versions

- .fvm/fvm_config.json
- CHANGELOG.md
- pubspec.lock
Bump fvm flutter SDK version and dependencies.
Shouldn't be any breaking changes but please double check 🙏.
> build: bump flutter sdk and dependencies versions

- CHANGELOG.md
- dev_tools/recipe_example.csv
- dev_tools/recipe_template.csv
- lib/home/widgets/recipes_screen.dart
- lib/home/widgets/sync_screen.dart
- lib/recipe/bloc/recipe_bloc.dart
- lib/recipe/bloc/recipe_event.dart
- lib/recipe/bloc/recipe_state.dart
- lib/recipe/widgets/ingredient_form.dart
- lib/recipe/widgets/recipe_details_screen.dart
- packages/gibsonify_api/lib/src/models/recipe.dart
- packages/gibsonify_api/lib/src/models/recipe_ingredient.dart
- packages/gibsonify_api/pubspec.yaml
- pubspec.lock
- pubspec.yaml
Main feature introduced is the addition of recipe importing functionality with a `.csv` file supplied as an input. Snackbar prompts tell user on status of recipe import. File picker dependency used is well liked on `pub.dev` but has [limited functionality](https://github.com/miguelpruivo/flutter_file_picker/issues/24) with restricting "all" file extensions - for our purposes, the package does not currently support limiting file selection to  `.csv` files. Hence, no file restriction is imposed.
Other changes are minor and mostly stylistic based on user feedback.
> feat(recipe): implement feedback on features

- CHANGELOG.md
- cz.yaml
- pubspec.yaml
> chore: release 1.2.0

- CHANGELOG.md
- lib/collection/view/finish_collection_page.dart
- lib/collection/widgets/first_pass_food_item_card.dart
- lib/collection/widgets/second_pass_food_item_card.dart
- lib/collection/widgets/sensitization_screen.dart
- lib/collection/widgets/third_pass_food_item_card.dart
- lib/recipe/widgets/ingredient_form.dart
- lib/recipe/widgets/recipe_details_screen.dart
- lib/recipe/widgets/recipe_probes_screen.dart
- pubspec.lock
- pubspec.yaml
Self explanatory. After the [dynamic sizing bug was fixed in dropdown search](https://github.com/salim-lachdhaf/searchable_dropdown/issues/407), this PR implements dynamic sizing of dropdowns, and thus closes #41.
> feat: add dynamic dropdown search sizing

- lib/collection/view/finish_collection_page.dart
- lib/collection/widgets/first_pass_food_item_card.dart
- lib/collection/widgets/measurement_card.dart
- lib/collection/widgets/second_pass_food_item_card.dart
- lib/collection/widgets/sensitization_screen.dart
- lib/import_export/bloc/import_export_bloc.dart
- lib/recipe/widgets/ingredient_form.dart
- lib/recipe/widgets/recipe_probes_screen.dart
- pubspec.lock
- pubspec.yaml
flutter_slidable: ^1.2.0 -> ^2.0.0
geolocator: ^8.0.5 -> ^9.0.2
dropdown_search: ^4.0.1 -> ^5.0.3
share_plus: ^4.0.4 -> ^6.2.0
package_info_plus: ^1.4.0 -> ^3.0.1
file_picker: ^4.4.0 -> ^5.2.2
permission_handler: ^9.2.0 -> ^10.2.0
flutter_launcher_icons: ^0.9.2 -> ^0.10.0
> chore: flutter pkgs major version upgrade

- lib/household/view/view_household.dart
- lib/household/view/view_respondent.dart
- Implements a much cleaner tabbed UI for the view household and view respondent pages
> feat(household): tabbed UI for household and respondent

- lib/households/bloc/households_bloc.dart
- lib/households/bloc/households_state.dart
> fix(households): cancel subscription on bloc close

- README.md
Fix the outdated link to my website that got rewritten by mistake [here](https://github.com/DigitalNutritionalAssessment/gibsonify/commit/3cf22e23ab88877095e6588aad939f2a32ce12f5#r89406155).
Thanks for all the work guys! 💙
> docs(readme): update author link

- lib/collection/bloc/collection_bloc.dart
- lib/collection/bloc/collection_event.dart
- lib/collection/widgets/sensitization_screen.dart
- lib/household/view/create_respondent.dart
- lib/household/view/edit_respondent.dart
- lib/household/view/view_respondent.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.g.dart
- packages/gibsonify_api/lib/src/models/respondent.dart
- packages/gibsonify_api/lib/src/models/respondent.g.dart
> feat: add missing Respondent information fields

- lib/household/view/edit_household.dart
- lib/households/bloc/households_bloc.dart
- lib/households/bloc/households_event.dart
- lib/households/bloc/households_state.dart
- lib/households/view/households.dart
- lib/import_export/bloc/import_export_bloc.dart
- lib/shared/shared.dart
- packages/gibsonify_api/lib/src/models/household.dart
- packages/gibsonify_repository/lib/src/isar.dart
Adds sorting by these fields on the view households screen:
- Household ID
- Sensitisation Date
- Distance
Partly addresses #78
> feat(households): sorting

- lib/home/widgets/settings_screen.dart
- lib/login/bloc/login_bloc.dart
- lib/login/bloc/login_event.dart
- lib/login/widgets/login_form.dart
- lib/surveys/view/create_survey.dart
- lib/surveys/view/surveys.dart
- lib/surveys/view/view_survey.dart
- packages/gibsonify_api/lib/src/models/login_info.dart
- Adds an option on login screen to indicate if user is a supervisor
- Only allows new survey creation if user is a supervisor
> feat(surveys): only supervisors can create surveys

- lib/app.dart
- lib/collection/bloc/collection_bloc.dart
- lib/collection/bloc/collection_event.dart
- lib/collection/bloc/collection_state.dart
- lib/collection/view/collection_page.dart
- lib/collection/view/finish_collection_page.dart
- lib/collection/view/third_pass_help_page.dart
- lib/collection/widgets/delete_food_item_dialog.dart
- lib/collection/widgets/first_pass_screen.dart
- lib/collection/widgets/fourth_pass_food_item_card.dart
- lib/collection/widgets/fourth_pass_screen.dart
- lib/collection/widgets/measurement_card.dart
- lib/collection/widgets/second_pass_food_item_card.dart
- lib/collection/widgets/second_pass_screen.dart
- lib/collection/widgets/sensitization_screen.dart
- lib/collection/widgets/third_pass_screen.dart
- lib/household/view/view_respondent.dart
- lib/recipe/widgets/recipe_details_screen.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.dart
- packages/gibsonify_repository/test/gibsonify_repository_test.dart
- pubspec.lock
- pubspec.yaml
- test/collection/collection_bloc_test.dart
Major UI improvements and technical debt clear up in collection form.
- Stepper layout (replacing tabbed layout)
- Added input validation (closes #61)
- Localised collection bloc
> feat(collection): major UI revamp and validation checks

- lib/collection/view/collection_page.dart
- lib/household/bloc/household_bloc.dart
- lib/household/bloc/household_event.dart
- lib/household/view/create_respondent.dart
- lib/household/view/edit_household.dart
- lib/household/view/edit_respondent.dart
- lib/household/view/view_household.dart
- lib/household/view/view_respondent.dart
- lib/households/view/create_household.dart
- lib/households/view/households.dart
- lib/main.dart
- lib/shared/shared.dart
- packages/gibsonify_api/lib/gibsonify_api.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.g.dart
- packages/gibsonify_api/lib/src/models/household.dart
- packages/gibsonify_api/lib/src/models/household.g.dart
- packages/gibsonify_api/lib/src/models/metadata.dart
- packages/gibsonify_api/lib/src/models/metadata.g.dart
- packages/gibsonify_api/lib/src/models/models.dart
- packages/gibsonify_api/lib/src/models/respondent.dart
- packages/gibsonify_api/lib/src/models/respondent.g.dart
- test/collection/collection_bloc_test.dart
Adds `createdAt`, `createdBy`, `lastModifiedAt`, `lastModifiedBy` fields to `Household`, `Respondent`, `GibsonsForm` (collection) for use in data sync
> feat(models): add metadata for sync

- packages/gibsonify_api/lib/src/models/anthropometrics.dart
- packages/gibsonify_api/lib/src/models/anthropometrics.g.dart
- packages/gibsonify_api/lib/src/models/food_item.dart
- packages/gibsonify_api/lib/src/models/food_item.g.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.dart
- packages/gibsonify_api/lib/src/models/gibsons_form.g.dart
- packages/gibsonify_api/lib/src/models/household.dart
- packages/gibsonify_api/lib/src/models/household.g.dart
- packages/gibsonify_api/lib/src/models/measurement.dart
- packages/gibsonify_api/lib/src/models/measurement.g.dart
- packages/gibsonify_api/lib/src/models/metadata.dart
- packages/gibsonify_api/lib/src/models/metadata.g.dart
- packages/gibsonify_api/lib/src/models/recipe.dart
- packages/gibsonify_api/lib/src/models/recipe.g.dart
- packages/gibsonify_api/lib/src/models/recipe_ingredient.dart
- packages/gibsonify_api/lib/src/models/recipe_ingredient.g.dart
- packages/gibsonify_api/lib/src/models/recipe_probe.dart
- packages/gibsonify_api/lib/src/models/recipe_probe.g.dart
- packages/gibsonify_api/lib/src/models/respondent.dart
- packages/gibsonify_api/lib/src/models/respondent.g.dart
- packages/gibsonify_api/lib/src/models/survey.dart
- packages/gibsonify_api/lib/src/models/survey.g.dart
- packages/gibsonify_api/pubspec.yaml
- packages/gibsonify_api/test/gibsonify_api_test.dart
Replaces manual JSON serialisation and deserialisation implementations with code generation from `json_serializable`. Number and complexity of types is increasing so this is essential.
> refactor(api): code generation for JSON serialisation and deserialisation

- lib/surveys/view/surveys.dart
- test/survey/survey_test.dart
- test/utils.dart
Adds checks:
- Only supervisors can delete surveys
- Only surveys that are not associated with any collections can be deleted
> feat(surveys): delete logic updates

- lib/household/view/view_household.dart
- lib/household/view/view_respondent.dart
- pubspec.lock
- pubspec.yaml
Adds small utilities to improve user experience when browsing through households and respondents:
- 'Show on map' button on household location
- 'Dial' button on respondent phone number
- More to be added
> feat: info utilities
